import { normalizeLocale } from '@/content/localizedContent'

const PROFILE_CONTENT = {
  ru: {
    levels: [
      { id: 'intern', label: 'Стажер', image: '/mascot2.png' },
      { id: 'junior', label: 'Младший инспектор', image: '/mascot3.png' },
      { id: 'revisor', label: 'Ревизор', image: '/mascot.png' },
      { id: 'senior', label: 'Старший инспектор', image: '/mascot4.png' },
      { id: 'expert', label: 'Эксперт', image: '/mascot3.png' },
      { id: 'master', label: 'Мастер ревизии', image: '/mascot2.png' },
    ],
    error: {
      eyebrow: 'Личный кабинет',
      title: 'Профиль временно недоступен',
      loadFailed: 'Не удалось загрузить профиль.',
      missingUserId: 'Идентификатор пользователя не указан.',
    },
    hero: {
      badge: 'Текущий уровень',
      levelLabel: 'Уровень',
      ofLabel: 'из',
      usernameLabel: 'Username',
      lightningsLabel: 'Молнии',
      experienceLabel: 'Опыт',
      lightningsUnit: 'молний',
    },
    personalInfo: {
      surnameLabel: 'Фамилия',
      nameLabel: 'Имя',
      usernameLabel: 'Username',
      phoneLabel: 'Номер телефона',
      confirmLabel: 'Подтвердить',
      logoutLabel: 'Выйти',
    },
    features: {
      title: 'Доступные возможности',
      mascotAlt: 'Маскот молний',
      currentBalanceLabel: 'Текущий баланс молний',
      exchangeLabel: 'Обменять молнии',
      actions: [
        'Отметить проблему на карте',
        'Создавать коллективные обращения',
        'Значок "Проверено"',
      ],
    },
    activity: {
      headers: ['Активность', 'Тема', 'Дата', 'Подтверждено', 'Молнии'],
      fallbackRows: [
        {
          activity: 'Подтвердил обращение',
          topic: 'Школа 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '2',
          lightning: '+15',
          isHighlighted: true,
        },
        {
          activity: 'Оставил жалобу',
          topic: 'Школа 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: 'Оставил жалобу',
          topic: 'Школа 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '10',
          lightning: '+15',
        },
        {
          activity: 'Оставил жалобу',
          topic: 'Ташкент',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: 'Оставил жалобу',
          topic: 'Ташкент',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: 'Оставил жалобу',
          topic: 'Ташкент',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: 'Оставил жалобу',
          topic: 'Ташкент',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: 'Оставил жалобу',
          topic: 'Ташкент',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: 'Подтвердил обращение',
          topic: 'Ташкент',
          date: '12.03.2025-11.12.2026',
          confirmed: '4',
          lightning: '+10',
        },
        {
          activity: 'Подтвердил обращение',
          topic: 'Ташкент',
          date: '12.03.2025-11.12.2026',
          confirmed: '2',
          lightning: '+10',
        },
      ],
    },
  },
  uzb: {
    levels: [
      { id: 'intern', label: 'Stajyor', image: '/mascot2.png' },
      { id: 'junior', label: 'Kichik inspektor', image: '/mascot3.png' },
      { id: 'revisor', label: 'Revizor', image: '/mascot.png' },
      { id: 'senior', label: 'Katta inspektor', image: '/mascot4.png' },
      { id: 'expert', label: 'Ekspert', image: '/mascot3.png' },
      { id: 'master', label: 'Reviziya ustasi', image: '/mascot2.png' },
    ],
    error: {
      eyebrow: 'Shaxsiy kabinet',
      title: 'Profil vaqtincha mavjud emas',
      loadFailed: "Profilni yuklab bo'lmadi.",
      missingUserId: 'Foydalanuvchi identifikatori ko‘rsatilmagan.',
    },
    hero: {
      badge: 'Joriy daraja',
      levelLabel: 'Daraja',
      ofLabel: '/',
      usernameLabel: 'Username',
      lightningsLabel: 'Molniyalar',
      experienceLabel: 'Tajriba',
      lightningsUnit: 'molniya',
    },
    personalInfo: {
      surnameLabel: 'Familiya',
      nameLabel: 'Ism',
      usernameLabel: 'Username',
      phoneLabel: 'Telefon raqami',
      confirmLabel: 'Tasdiqlash',
      logoutLabel: 'Chiqish',
    },
    features: {
      title: 'Mavjud imkoniyatlar',
      mascotAlt: 'Molniyalar maskoti',
      currentBalanceLabel: 'Joriy molniyalar balansi',
      exchangeLabel: 'Molniyalarni almashtirish',
      actions: [
        "Xaritada muammoni belgilash",
        "Jamoaviy murojaatlar yaratish",
        '"Tasdiqlangan" belgisi',
      ],
    },
    activity: {
      headers: ['Faollik', 'Mavzu', 'Sana', 'Tasdiqlangan', 'Molniyalar'],
      fallbackRows: [
        {
          activity: 'Murojaatni tasdiqladi',
          topic: 'Maktab 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '2',
          lightning: '+15',
          isHighlighted: true,
        },
        {
          activity: "Shikoyat qoldirdi",
          topic: 'Maktab 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: "Shikoyat qoldirdi",
          topic: 'Maktab 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '10',
          lightning: '+15',
        },
        {
          activity: "Shikoyat qoldirdi",
          topic: 'Toshkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: "Shikoyat qoldirdi",
          topic: 'Toshkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: "Shikoyat qoldirdi",
          topic: 'Toshkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: "Shikoyat qoldirdi",
          topic: 'Toshkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: "Shikoyat qoldirdi",
          topic: 'Toshkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: 'Murojaatni tasdiqladi',
          topic: 'Toshkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '4',
          lightning: '+10',
        },
        {
          activity: 'Murojaatni tasdiqladi',
          topic: 'Toshkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '2',
          lightning: '+10',
        },
      ],
    },
  },
  en: {
    levels: [
      { id: 'intern', label: 'Intern', image: '/mascot2.png' },
      { id: 'junior', label: 'Junior inspector', image: '/mascot3.png' },
      { id: 'revisor', label: 'Revisor', image: '/mascot.png' },
      { id: 'senior', label: 'Senior inspector', image: '/mascot4.png' },
      { id: 'expert', label: 'Expert', image: '/mascot3.png' },
      { id: 'master', label: 'Master reviewer', image: '/mascot2.png' },
    ],
    error: {
      eyebrow: 'User cabinet',
      title: 'Profile is temporarily unavailable',
      loadFailed: 'Could not load the profile.',
      missingUserId: 'User id is missing.',
    },
    hero: {
      badge: 'Current level',
      levelLabel: 'Level',
      ofLabel: 'of',
      usernameLabel: 'Username',
      lightningsLabel: 'Lightnings',
      experienceLabel: 'Experience',
      lightningsUnit: 'lightnings',
    },
    personalInfo: {
      surnameLabel: 'Surname',
      nameLabel: 'Name',
      usernameLabel: 'Username',
      phoneLabel: 'Phone number',
      confirmLabel: 'Confirm',
      logoutLabel: 'Log out',
    },
    features: {
      title: 'Available features',
      mascotAlt: 'Lightnings mascot',
      currentBalanceLabel: 'Current lightning balance',
      exchangeLabel: 'Exchange lightnings',
      actions: [
        'Mark an issue on the map',
        'Create collective appeals',
        'Verified badge',
      ],
    },
    activity: {
      headers: ['Activity', 'Topic', 'Date', 'Confirmed', 'Lightnings'],
      fallbackRows: [
        {
          activity: 'Verified report',
          topic: 'School 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '2',
          lightning: '+15',
          isHighlighted: true,
        },
        {
          activity: 'Submitted report',
          topic: 'School 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: 'Submitted report',
          topic: 'School 45',
          date: '12.03.2025-11.12.2026',
          confirmed: '10',
          lightning: '+15',
        },
        {
          activity: 'Submitted report',
          topic: 'Tashkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: 'Submitted report',
          topic: 'Tashkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+15',
        },
        {
          activity: 'Submitted report',
          topic: 'Tashkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: 'Submitted report',
          topic: 'Tashkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: 'Submitted report',
          topic: 'Tashkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '5',
          lightning: '+10',
        },
        {
          activity: 'Verified report',
          topic: 'Tashkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '4',
          lightning: '+10',
        },
        {
          activity: 'Verified report',
          topic: 'Tashkent',
          date: '12.03.2025-11.12.2026',
          confirmed: '2',
          lightning: '+10',
        },
      ],
    },
  },
}

export function getProfileContent(locale) {
  return PROFILE_CONTENT[normalizeLocale(locale)] ?? PROFILE_CONTENT.ru
}
